# escape=`



# Build off nanoserver container
FROM microsoft/dotnet:2.1-sdk-nanoserver-1803

ENV JAVA_PKG=server-jre-8u181-windows-x64.tar.gz `
    JAVA_HOME=C:\jdk1.8.0_181

ADD $JAVA_PKG \

RUN setx /M PATH %PATH%;%JAVA_HOME%\bin

ENV GIT_VERSION 2.15.1
ENV GIT_PATCH_VERSION 2RUN powershell -Command $ErrorActionPreference = 'Stop' ; `
   [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 ; `
   Invoke-WebRequest $('https://github.com/git-for-windows/git/releases/download/v{0}.windows.{1}/MinGit-{0}.{1}-busybox-64-bit.zip' -f $env:GIT_VERSION, $env:GIT_PATCH_VERSION) -OutFile 'mingit.zip' -UseBasicParsing ; `
   Expand-Archive mingit.zip -DestinationPath c:\mingit ; `
   Remove-Item mingit.zip -Force ; `
   setx /M PATH $('c:\mingit\cmd;{0}' -f $env:PATH)


SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]


RUN setx /M PATH $($env:Path.TrimEnd(';') +';' + $env:JAVA_HOME + '\bin;' + $env:GIT_HOME +'\cmd;' + $env:GIT_HOME +'\usr\bin;')


#Copy launch script used by entry point
COPY "slave-launch.ps1" ".\slave-launch.ps1"

ENV SLAVE_FILENAME=slave.jar `
    REMOTING_VERSION=3.15

ENV SLAVE_HASH_FILENAME=$SLAVE_FILENAME.sha1

# Get the Slave from the Jenkins Artifacts Repository
RUN Invoke-WebRequest "https://repo.jenkins-ci.org/public/org/jenkins-ci/main/remoting/$env:REMOTING_VERSION/remoting-$env:REMOTING_VERSION.jar" -OutFile $env:SLAVE_FILENAME -UseBasicParsing; `
    Invoke-WebRequest "https://repo.jenkins-ci.org/public/org/jenkins-ci/main/remoting/$env:REMOTING_VERSION/remoting-$env:REMOTING_VERSION.jar.sha1" -OutFile $env:SLAVE_HASH_FILENAME -UseBasicParsing; `
if ((Get-FileHash $env:SLAVE_FILENAME -Algorithm SHA1).Hash -ne $(Get-Content $env:SLAVE_HASH_FILENAME)) {exit 1};




ENTRYPOINT .\slave-launch.ps1

# Find Jenkins LTS version https://jenkins.io/changelog-stable/
LABEL application-min-version.jenkins="2.85.0" `
    application-min-version.jenkins-lts="2.89.2" `
    application-version.jenkins-remoting="3.15" `
    application-version.windows="sac2016" `
    application-version.jdk="1.8" `
application-version.git="2.15.1.2"


ENTRYPOINT .\slave-launch.ps1

